abstract: Smart URI fetching/caching
author: Benjamin Trott <ben+cpan@stupidfool.org>
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: URI-Fetch
no_index:
  directory:
    - t
    - inc
    - t
recommends:
  Cache: 0
  Compress::Zlib: 0
requires:
  Class::ErrorHandler: 0
  LWP: 0
  Storable: 0
  URI: 0
version: 0.08
