name: URI-Fetch
version: 0.04
abstract: Smart URI fetching/caching
author: Benjamin Trott <ben+cpan@stupidfool.org>
license: perl
distribution_type: module
requires:
  Class::ErrorHandler: 0
  LWP: 0
  URI: 0
  Storable: 0
recommends:
  Compress::Zlib: 0
  Cache: 0
no_index:
  directory:
    - t
    - inc
generated_by: Module::Install version 0.36
